//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artistrelease
    {
        public int id { get; set; }
        public int artistid { get; set; }
        public int releaseid { get; set; }
        public int artistcount { get; set; }
    
        public virtual artist artist { get; set; }
        public virtual release release { get; set; }
    }
}
