//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class release
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public release()
        {
            this.artistreleases = new HashSet<artistrelease>();
        }
    
        public int id { get; set; }
        public System.Guid globalid { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public string label { get; set; }
        public string mediatype { get; set; }
        public Nullable<System.DateTime> releasedate { get; set; }
        public string language { get; set; }
        public string additionaldetails { get; set; }
        public Nullable<int> trackscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artistrelease> artistreleases { get; set; }
    }
}
